version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: api_service
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    command: python3 app.py

  swagger-codegen:
    image: swaggerapi/swagger-codegen-cli-v3
    container_name: swagger_codegen
    volumes:
      - StravaPythonClient:/output
    command: generate -i https://developers.strava.com/swagger/swagger.json -l python -o /output