services:
  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    command: fastapi run
# docker exec -it db_service psql -U user -d stronger_together
  db:
    image: postgres:latest
    container_name: db_service
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stronger_together
    ports:
      - "5432:5432"

  swagger-codegen:
    image: swaggerapi/swagger-codegen-cli-v3
    container_name: swagger_codegen
    volumes:
      - ./StravaPythonClient:/output
    command: generate -i https://developers.strava.com/swagger/swagger.json -l python -o /output

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak_service
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db_service
      KC_DB_URL_DATABASE: stronger_together
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./keycloak:/opt/keycloak/data/import
  
  client:
    build:
      context: ./web_client
      target: builder
    container_name: client
    ports:
      - "3000:3000"
    # volumes:
    #   - ./client:/app
    command: npm run dev
  prod_client:
    build:
      context: ./web_client
      target: production
    container_name: prod_client
    ports:
      - "3000:3000"
   